### ISSUE TITLE
How to get Progress of Zipping and Unzipping a folder  ?

### ISSUE THREAD

**Issue by goxr3plus** [zeroturnaround/zt-zip#106]
Just found this amaaaazziiing library !!!!! :1st_place_medal: 

I have a question thought :+1: 

``ZipUtil.pack(new File("/tmp/demo"), new File("/tmp/demo.zip"));``

Let's say i am packing a directory to a zip folder .... how i can get the progress of packing , i mean let's say it is 1 GB it will take some time to zip right ? I want the user to get notified about the progress ..

So let's say are there any listeners on the library so i can have a local variable holding the progress ?

Same for the unzipping :) 

THANK YOUUUU SOOOO MUCH!!!!!!

**Comment by toomasr** [comment]
We never implemented a progress bar for zt-zip. The closest to this is a example project at https://github.com/toomasr/zt-zip-progress-bar which shows an approach to implementing one.

Another approach is somewhat documented at https://github.com/zeroturnaround/zt-zip/issues/26

**Comment by goxr3plus** [comment]
This is very great ♥, how about adding this capability inaide the library i
started using it with a big github project to avoid writing 100 lines of
code but now adding a progress bar seems again to need a lot of code lines
:)

Would you submit rhia new feature plizzzz :)

**Comment by toomasr** [comment]
I don't have a clear idea on how to add it in a way that it would make sense at the moment :(. I believe this is easier to be implemented in user's code rather than in the lib to have more flexibility.

**Comment by penn5** [comment]
I agree, the actual addition to the code is only ~6 lines anyway...

**Comment by toomasr** [comment]
Ok, will do!
