### ISSUE TITLE
Any way to cancel ZipUtil `Pack` and `UnPack` methods

### ISSUE THREAD

**Issue by goxr3plus** [zeroturnaround/zt-zip#108]
I am using multiple Threads which have the ability to be cancelled by the user , how i can cancel the following procedures ?

```JAVA
//Pack
ZipUtil.pack(new File("/tmp/demo"), new File("/tmp/demo.zip"), new NameMapper() {
  public String map(String name) {
    return "foo/" + name;
  }
});
```

//Unpack
....

Do i need just to return ```null``` or i have to do something more smart ?

**Comment by toomasr** [comment]
You can throw an exception from the method to get out of it. If a user cancels what is the expectation? This is the code that executes https://github.com/zeroturnaround/zt-zip/blob/master/src/main/java/org/zeroturnaround/zip/ZipUtil.java#L1545 Let me know if this helps you.

**Comment by goxr3plus** [comment]
Thank you very much, i just return null and it throws an exceptio  much love for answering :) :)
