### ISSUE TITLE
How to pack entry directly to zip

### ISSUE THREAD

**Issue by goxr3plus** [zeroturnaround/zt-zip#121]
The problem which i have is that i have one file which i directly want to pack to zip file.

Let's say i want the below to work for single not directory file too .

`ZipUtil.pack(new File("/tmp/demo"), new File("/tmp/demo.zip"));`

This in the current moment can only be used for directories but i want it to be used with single files for example :

`ZipUtil.pack(new File("/tmp/demo.txt"), new File("/tmp/demo.zip"));`

The final zip will just contain the `demo.txt`

**Comment by toomasr** [comment]
You must be looking for the `ZipUtil.packEntry` method. See the example here https://github.com/zeroturnaround/zt-zip#compress-a-file-into-a-zip-archive

**Comment by goxr3plus** [comment]
SUPERRR THANK YOU :)
