### ISSUE TITLE
Populating a zip file over time / one by one without copying the archive over and over again

### ISSUE THREAD

**Issue by mar1ged** [zeroturnaround/zt-zip#126]
I have a question that is somehow related to my previous [issue](https://github.com/zeroturnaround/zt-zip/issues/113).

My current task is to create a quite big zip file. The overall process of creating the zip file will take hours, from time to time I will have to add a new file. At the end I will "close" the zip file.

I want to avoid copying the current zip to a new zip when adding the new file.
And I want to avoid buffering the files in `ZipEntrySource`s or even on disk.

Is this possible (with your API) ?

**Comment by toomasr** [comment]
I believe we don't have anything like that. The underlying API does have support for that since Java 7 though.

Best bet right now would be https://stackoverflow.com/a/17504151/161575

**Comment by mar1ged** [comment]
Thanks a lot. I would like to use the added value of your API and use the same library for all ZIP file handling (I need to do more than what I described earlier). So I think I will investigate alternatives.
