### ISSUE TITLE
Bug: "only DEFLATED entries can have EXT descriptor"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [zeroturnaround/zt-zip#131]
Sometimes when I try to open a zip file, I get this error:

```
    org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at org.zeroturnaround.zip.ZipExceptionUtil.rethrow(ZipExceptionUtil.java:11)
        at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:729)
        at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:746)
        at com.lb.ziptest.MainActivity$onCreate$1.invoke(MainActivity.kt:19)
        at com.lb.ziptest.MainActivity$onCreate$1.invoke(MainActivity.kt:14)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
     Caused by: java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
        at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:321)
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
        at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:710)
        at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:746) 
        at com.lb.ziptest.MainActivity$onCreate$1.invoke(MainActivity.kt:19) 
        at com.lb.ziptest.MainActivity$onCreate$1.invoke(MainActivity.kt:14) 
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) 

```

How come?
Attached sample project and sample ZIP file.
Tested on Android 9.

[test.zip](https://github.com/zeroturnaround/zt-zip/files/4404002/test.zip)

[ZipTest.zip](https://github.com/zeroturnaround/zt-zip/files/4404008/ZipTest.zip)

**Comment by toomasr** [comment]
It is a limitation of the underlying JDK zip handling - https://bugs.openjdk.java.net/browse/JDK-8143613 All the Zip handling libraries that are based on the JDK ZipInputStream have this problem.

One workaround is not to use the streaming api but instead unpacking the archive and then packing it again after doing the transformations on disk. Of course the viability of this option will depend heavily on your use case.

**Comment by AndroidDeveloperLB** [comment]
Is there any library that overcomes it, for Android ? 
One that lets me iterate over the items without actually extracting them, and letting me get a stream from specific entries that I want, like on ZipInputStream?

Extracting files is wasteful. Also, testing on Android R emulator, even that won't work, as ZipFile can't handle it either:
https://issuetracker.google.com/issues/152802775

So this workaround that you've suggested isn't efficient and isn't guaranteed to work either.
What's so special about this kind of zip file? How come on PC I can open it easily? How do apps on the PC handle this kind of zip files?

**Comment by toomasr** [comment]
I guess this has the best explanation in the first answer - https://stackoverflow.com/questions/47208272/android-zipinputstream-only-deflated-entries-can-have-ext-descriptor

Another possible workaround is that you only process archives that are compressed with STORE rather than DEFLATE. Not sure if that is an option for you.

I do know numerous zip libraries but I don't know if any of them in the Java space is not using the underlying Java API. I did start writing one years ago but I gave up couple of weeks into it :)

**Comment by AndroidDeveloperLB** [comment]
I can't force all users in the world to use one kind of zip file and all servers to hold only those. :)

Also I don't even know how to get the type of the zip file. What about [7-zip](https://www.7-zip.org/) on PC? It's open sourced, and it's the one I use and it can open those files. Sadly not in Java/Kotlin, though.

**Comment by toomasr** [comment]
I was thinking that if your zip file goes through a server before it lands on your Android app you can preprocess it.

Apps that don't use the JDK Zip handling don't have that problem. 7-zip, winzip, zip etc. are non-java.

**Comment by AndroidDeveloperLB** [comment]
Did you check the link ?

**Comment by toomasr** [comment]
Yup. The page sais 

> 7-Zip-JBinding is a java wrapper for 7-Zip C++ library

This means that underlying logic is in C++ and there is Java put around it so that easier to use from Java. This means that it is not relying on JDK implementation but its own.

**Comment by AndroidDeveloperLB** [comment]
So it can be a good solution for Android?

**Comment by toomasr** [comment]
I don't know about the native code in Android and I have not done any Android development for years. The only way you can get this to work if the underlying C++ libraries work in Android.

The best advice I can give you is to look for non-jdk based zip libraries that work in Android. I'll close off this thread as we are getting out of zt-zip discussions.

**Comment by AndroidDeveloperLB** [comment]
Oh sorry for that.
Can you please check it out though, without trying on Android?
zt-zip could use it for itself too, as it can't open all zip files currently.

**Comment by toomasr** [comment]
As 7-Zip-JBinding already does the wrapping then there is little point in zt-zip to do the same. The idea of zt-zip is having an API that is easy to use for most common operations. These kind of edge cases on Android environment is something that I cannot help with especially if there are no good simple solutions available.

**Comment by AndroidDeveloperLB** [comment]
Aren't the same issues exist on PC too?

**Comment by toomasr** [comment]
They do but it does not seem a common problem. Based on casual googling and reading mailinglists it seems that it only arises with a very few zip archives from specific tool versions so I guess not that many such zip archives are floating around or being produced and then stream processed.

zt-zip has been around for a decade or so and this is the first time I see this problem. Googling shows that other people have had this problem though.

**Comment by AndroidDeveloperLB** [comment]
Would it be possible for you to use this for zt-zip?
How much would it enlarge the library?

**Comment by toomasr** [comment]
No plan to change the underlying zip implementation of zt-zip. I have no idea whether it would enlarge or not and how much.

**Comment by AndroidDeveloperLB** [comment]
Zip implementation? But you said it uses the one of the framework, and that it doesn't work for some zip files...
Isn't the point of this library to handle zip files?
