### ISSUE TITLE
ZipUtil cannot be resolved even I have added its maven dependency

### ISSUE THREAD

**Issue by SK-Yang** [zeroturnaround/zt-zip#145]
My eclipse cannot resolve the example that is written in readme.md.

- boolean exists = ZipUtil.containsEntry(new File("/tmp/demo.zip"), "foo.txt");

It will just tell me "ZipUtil cannot be resolved to a type", and I have done of add it into pom and do maven update.
My other dependencies like httpclient and Gson are fine, so I suppose there is something wrong with those examples?

**Comment by toomasr** [comment]
Can you share the pom.xml or the zt-zip dependency part of it?

**Comment by slandelle** [comment]
You should make sure the zt-zip dependency in your local maven cache isn’t corrupted. Remove it and re-trigger the download.

**Comment by SK-Yang** [comment]
After restart the Eclipse, it seem like it can resolve its package name again.
Well, it's Eclipse...
