### ISSUE TITLE
Make ZipUtil.pack more memory efficient for large directories

### ISSUE THREAD

**Issue by bradical** [zeroturnaround/zt-zip#35]
Consider calling [`dir.list()`](http://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()) or using [`Files.walkFileTree`]() (if you're fortunate enough to be able to use Java 1.7+) instead of [`File.listFiles()` in ZipUtil.pack](https://github.com/zeroturnaround/zt-zip/blob/62a6b8516a15bec81f96d4f393375e5ab60c1b36/src/main/java/org/zeroturnaround/zip/ZipUtil.java#L1135)

This is something I just ran into recently with our own code to zip up directories so I started looking around for a fast/efficient library that would handle this for me.

In my case, I was zipping up a directory with 800,000 files in it (all at one level) and found that my program's memory was increasing by 500MB due to all of the File objects created by File.listFIles(). File.list() was about 50% less memory with just the string paths. You have to load each File individually but then you can allow it to be GC'ed. But the big savings came when using [Files.walkFileTree(Path,FileVisitor)](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#walkFileTree(java.nio.file.Path, java.nio.file.FileVisitor)). Both of these are probably a bit slower for smaller directories.

**Comment by nemecec** [comment]
zt-zip 1.9 has been released, containing the above mentioned improvements.
