### ISSUE TITLE
Is there anyway to completely add a folder to an existing zip?

### ISSUE THREAD

**Issue by dominic69** [zeroturnaround/zt-zip#63]
i.e. can we do this without creating a new zip? In zip4j we have "ZipUpdate" class to do the same...

**Comment by toomasr** [comment]
Does the addOrReplaceEntries apply to your use case? I've added an example to the readme, see https://github.com/zeroturnaround/zt-zip#add-or-replace-entries-in-a-zip-archive

**Comment by dominic69** [comment]
Doesn't this create a new zip rather than editing or appending a file to the existing zip? I'm modifying an android apk file which is a sort of zip file but some files go missing in the newly created zip by zt-zip. I currently use zip4j which does my job but it takes much more time to do so. Your library is speedier and quite efficient imo.

**Comment by toomasr** [comment]
This method will update the ZIP archive in place. Do you have an example with code where zt-zip fails for you?

**Comment by dominic69** [comment]
The eg. you linked above replaces single files, right? How do I add/append an entire folder to the zip? Or am I being stupidly missing something?

Thanks for the tool...

**Comment by toomasr** [comment]
You would need to iterate the folders, gather all the files you want to update and provide them as an argument to the method.

**Comment by shelajev** [comment]
Currently, zt-zip doesn't have public desctructive operations. There's a private method that does what you want: https://github.com/zeroturnaround/zt-zip/blob/master/src/main/java/org/zeroturnaround/zip/ZipUtil.java#L2433

I think we might add a public api if make it absolutely clear that it's destructive. @dominic69 what API do you need the most? Maybe you could form a PR?

**Comment by dominic69** [comment]
I just tried the method...Thanks. Its slower than zip4j, so I use zt-zip for all extraction purposes and for updating single file purposes...FYI, zt-zip is roughly 40% FASTER at extraction compared to zip4j...Thanks a ton again!
