### ISSUE TITLE
Packing EPUB3

### ISSUE THREAD

**Issue by rahmanusta** [zeroturnaround/zt-zip#65]
I have an epub directory that must be zipped with following requirements;

Epub Directory 

 - META-INF/
 - OEBPS/
 - mimetype

mimetype file must be first entry in zip file with no compression
OEBPS and META-INF directories and theirs subdirs and subfiles can be compressed in any level

When I use ZipUtil.pack method, everything is good but mimetype file does not first entry in zip file.

How can I do that with zt-zip ?

**Comment by reinra** [comment]
Unfortunately ZipUtil is not flexible enough for such scenario. You need a custom code for packing such an archive.

**Comment by rahmanusta** [comment]
Thanks.

**Comment by mrifni** [comment]
have you found a solution for this ?
