### ISSUE TITLE
How to create zip in memory?

### ISSUE THREAD

**Issue by vach** [zeroturnaround/zt-zip#67]
I'm trying to get byte[] of the zip (i dont want to actualy do IO to file) from multiple ZipByteSource's but i cant find any suitable api for that. Is it possible with this library?

**Comment by toomasr** [comment]
@vach can you take a look at the changes from @nemecec  and see if this is what you are looking for?

**Comment by nemecec** [comment]
I assume by `ZipByteSource` you mean `ByteSource`?

Example from https://github.com/zeroturnaround/zt-zip/blob/master/README.md, adjusted for your case, making use of my recent patches:

#### Add an entry from two byte arrays to a byte array output stream
```java
ZipEntrySource[] entries = new ZipEntrySource[] {
    new ByteSource("foo.txt", "foo".getBytes()),
    new ByteSource("bar.txt", "bar".getBytes())
};
OutputStream out = null;
byte[] zipBytes = null;
try {
  out = new ByteArrayOutputStream();
  ZipUtil.pack(entries, out);
  zipBytes = out.toByteArray();
}
finally {
  IOUtils.closeQuietly(out);
}
// zipBytes now contains all the bytes of the ZIP archive
```

And, if you want to update an existing archive, you need to use the `ZipUtil.addEntries(InputStream, ZipEntrySource[], OutputStream)` method.

**Comment by nemecec** [comment]
zt-zip 1.9 has been released, containing the above mentioned improvements.
