### ISSUE TITLE
It does not support unicode character set

### ISSUE THREAD

**Issue by gam2046** [zeroturnaround/zt-zip#68]
If the compressed file exists unicode character file name (such as Chinese, Japanese, etc.), will result in an exception.
Then I basically looked at the source code, this project is java.util.zip package. The default is to use hard-coded java.util.zip, thus resulting in a non-Western character does not work properly.

**Comment by toomasr** [comment]
Can you post your exact use case where it is failing? We do have added Charset options for some methods but not sure we've covered all. Definitely this is something that requires Java1.7. See https://github.com/zeroturnaround/zt-zip/blob/master/src/test/java/org/zeroturnaround/zip/UmlautTest.java

**Comment by gam2046** [comment]
Very grateful, I try to manually specify the character set and successfully extract the files.
However, I found the character set of the compressed file with the operating system character set has a relationship, I try at Chinese of Windows via "7-Zip" compress a ZIP file, it uses the GBK character set, rather than UTF8.
In other words, not all non-ASCII characters are used UFT8, which for me is a challenge. But your project is perfect. Thanks again!
