### ISSUE TITLE
Can not unpack zip with original structure

### ISSUE THREAD

**Issue by hfzzztz** [zeroturnaround/zt-zip#69]
Version 1.7
When I unpacking a zip file containing folders in Linux, all the entries in the zip are unpacked with name containing it's parent folders' names. Folders are omitted. But on windows everything is fine. Even on Linux some zip file can be unpacked correctly, while some can not.
Is anything wrong? Thanks for your help.

Structure of zip
![image](https://cloud.githubusercontent.com/assets/3377898/9990475/3ecb6906-6094-11e5-9369-ffea6df52e24.png)

Entries unpacked
![image](https://cloud.githubusercontent.com/assets/3377898/9990485/49ef43fc-6094-11e5-879b-ff18e2bc7c9b.png)

**Comment by toomasr** [comment]
Can you share the code you use to unpack archives with zt-zip?

**Comment by hfzzztz** [comment]
I use this API to unpack zip file.
ZipUtil.unpack(new ByteArrayInputStream(productData), tempDir);
Thanks

**Comment by toomasr** [comment]
Yup, that could cause this. I'll try to create some zip archives and see from there.

**Comment by toomasr** [comment]
Based on the Zip specification ( https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT ) everything must be forward slash. Can you share an archive that produces the problems you are having?

**Comment by hfzzztz** [comment]
I am sorry that I can not share these archives for these archives may contains confidential information. But   these archives are produced on windows using File.separator that is '\' as separator.
Thanks for your help.

**Comment by toomasr** [comment]
Can you create an archive that has the \ in it that you can share? I tried with Windows compression to get the archive that wouldn't work but I couldn't.

**Comment by hfzzztz** [comment]
I might confused you. The archive that wouldn't work was created by another program, not zt-zip. That program use File.separator as separator. zt-zip does not.
At first I doubt if there is anything wrong with zip unpacking functionality. But now I think it is not zt-zip's bug.

**Comment by toomasr** [comment]
I think I do understand. The spec says that the only separator should be a forward slash (/) but some software out there also creates with a separator that is a backslash (\).

zt-zip will never start creating these archives. If there are enough of these wrong archives on the internet then we can add support to unpacking these BUT I haven't found such archives yet.

**Comment by hfzzztz** [comment]
I create a zip taking '\' as separator. On Windows this zip can be unpack correctly because Windows takes '\' as separator too. 
Here is the result I unpacked on Linux.
![image](https://cloud.githubusercontent.com/assets/3377898/10091281/bfae5b6c-636b-11e5-864d-963de1baf957.png)
I send the zip file to your email.

**Comment by toomasr** [comment]
Thank you for providing the test archive. I did some work on the library on Friday. I added a BackslashUnpacker. You can see the usage at https://github.com/zeroturnaround/zt-zip/blob/master/src/test/java/org/zeroturnaround/zip/ZipUtilTest.java#L847 Let me know if this fixes the issue for you.

**Comment by nemecec** [comment]
zt-zip 1.9 has been released, containing the above mentioned improvements.
