### ISSUE TITLE
ZipsTest.testPreservingTimestamps is failing

### ISSUE THREAD

**Issue by toomasr** [zeroturnaround/zt-zip#73]
The [testPreservingTimestamps](https://github.com/zeroturnaround/zt-zip/blob/master/src/test/java/org/zeroturnaround/zip/ZipsTest.java#L162) unit test is failing. Debugging it further I noticed that after repacking we've lost the lastModifiedTime for the ZipEntries. This is quite important because if this is null it will fall back to some conversion. See the [getTime](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/f1f3f9eaf7fa/src/share/classes/java/util/zip/ZipEntry.java#l190) method from ZipEntry.

The conversion itself is in [extendedDosToJavaTime](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/f1f3f9eaf7fa/src/share/classes/java/util/zip/ZipUtils.java#l87) method. 

The documentation says "Converts extended DOS time to Java time, where up to 1999 milliseconds might be encoded into the upper half of the returned long". I bet this "might be encoded" is the reason why the test is off by 1 second when we lose the mtime field contents.

I've been able to consistently reproduce this error but others haven't hit it at all. As a solution I propose setting the field when using JDK8. I'll have a patch ready shortly.

**Comment by nemecec** [comment]
The issue does not manifest itself on older versions of Java 8 (at least 1.8.0_45 on OS X and 1.8.0_31 on Linux). Newer versions of Java 8 seem to have fixed the timestamp handling (tested with 1.8.0_65 on OS X and 1.8.0_66 on Linux).

**Comment by toomasr** [comment]
I'm closing the issue as we have merged the code that actually does a very granular setting of time (setLastModifiedTime, setCreationTime, setLastAccessedTime) for JDK8 and this gets us passed the weirdness.
