### ISSUE TITLE
Cannot delete the created file after using this library to create a zip file.

### ISSUE THREAD

**Issue by XHotSniperX** [zeroturnaround/zt-zip#75]
I am using this library to zip a directory and it works very well. The problem is, I can't delete the zip file afterwards because the file is in use. I can't delete it manually in the Windows Explorer either because of same problem. Only when I terminate the Java application I can delete the file.

I am creating the file like this:

```java
File exportFile = new File("output/export.zip");
try {
  ZipUtil.pack(new File("output/export"), exportFile);
} catch (Exception e) {
}
```

What am I doing wrong?

**Comment by toomasr** [comment]
You're doing everything right. I see that we are closing the streams fine. Need to double check on an actual Windows machine.

@reinra can you take a look?

**Comment by reinra** [comment]
I could not reproduce the issue on Windows.
Do you also access the ZIP file from your application after it's created?
Btw. please don't swallow any exceptions like your'e doing in your example. Just throw it upwards or wrap it if necessary.

**Comment by XHotSniperX** [comment]
Thanks for the answers. I am not accessing the file after I create it but I am using a jetty resource handler on the "output" folder. Could be that. I'll check it today and let you know.

**Comment by XHotSniperX** [comment]
Looks like the jetty part is causing it. Closing the issue here. Thank you again :)
