### ISSUE TITLE
Path support

### ISSUE THREAD

**Issue by revof11** [zeroturnaround/zt-zip#80]
This is great for basic File work.  However, for using [Jimfs](https://github.com/google/jimfs) and other stuff that is supported through [J7+ Paths](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html) it would be nice to be able to use the new "standard" if we could.  It's not so bad to get rolling and I could probably create some utility methods that do the conversion on the [ZipUtil](https://github.com/zeroturnaround/zt-zip/blob/master/src/main/java/org/zeroturnaround/zip/ZipUtil.java) root class.

**Comment by toomasr** [comment]
I don't have any experience with Jimfs. Not sure how to tackle this. @reinra do you have any ideas?

**Comment by reinra** [comment]
For ZipInpuStream we can use any InputStream as input (Files.newInputStream(Path)) but ZipFile constructors only accept File instances. So I'm not sure if that's ok with jimfs?
