### ISSUE TITLE
Error when unzip file

### ISSUE THREAD

**Issue by fjtorres** [zeroturnaround/zt-zip#87]
Hello.

I am using this library to unzip a file in a desktop application but I have an error with this stacktrace. The problem occurs sometimes and I don't found any cause or solution.

```
Caused by: java.util.zip.ZipException: invalid stored block lengths 
    at java.util.zip.InflaterInputStream.read(Unknown Source) 
    at java.io.FilterInputStream.read(Unknown Source) 
    at org.zeroturnaround.zip.commons.IOUtils.copyLarge(IOUtils.java:322) 
    at org.zeroturnaround.zip.commons.IOUtils.copyLarge(IOUtils.java:299) 
    at org.zeroturnaround.zip.commons.IOUtils.copy(IOUtils.java:274) 
    at org.zeroturnaround.zip.commons.FileUtils.copy(FileUtils.java:56) 
    at org.zeroturnaround.zip.ZipUtil$Unpacker.process(ZipUtil.java:964) 
    at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:425) 
```

This is the call to unzip the file `ZipUtil.unpack(file, outputDir)`

This is the version of the library in my `pom.xml` file.

```
<dependency>
	<groupId>org.zeroturnaround</groupId>
	<artifactId>zt-zip</artifactId>
	<version>1.10</version>
</dependency>
```

**Comment by toomasr** [comment]
Do you happen to have any of the ZIP files that produce this error? Do you know which JVM version this happens with?

**Comment by fjtorres** [comment]
I don't know the JVM version but I will try to get this information. The ZIP file is a new version of a desktop application and the problem doesn't occurs in all computer that use this desktop application.

**Comment by toomasr** [comment]
So the same ZIP archive sometimes causes problems and sometimes not? From the exception it feels that the ZIP archive might be corrupt (invalid stored block lengths) so I would presume it always fails. Another possibility is that it only fails with a certain JVM version.

So best would be to get our hands on the ZIP archive that produces the exception.

**Comment by fjtorres** [comment]
Yes, the same ZIP file sometimes fail and other times it is unzip correctly. I have requested information about the JVM to a co-worker.

If the problem might be that the file is corrupt maybe the download of the file from our web site could be the problem. I use `commons-io 2.5` to download file from our web site.

`FileUtils.copyURLToFile(new URL(downloadUrl), file)`

**Comment by toomasr** [comment]
Let me know if you have any more information - like the archive itself and then I can look into.

@reinra do you have any other ideas here?

**Comment by reinra** [comment]
Since Java 7 ZipFile uses UTF-8 by default. Not sure what did it use before that.
Maybe using wrong charset results in that error.

**Comment by fjtorres** [comment]
Please I will close this issue while I am working to verify the file downloaded with a checksum verification. Maybe the file is corrupted.
