### ISSUE TITLE
A created ZipInputStream is never closed and this causes a resource leakage

### ISSUE THREAD

**Issue by lhotari** [zeroturnaround/zt-zip#89]
When using [`org.zeroturnaround.zip.ZipUtil#iterate(java.io.InputStream, org.zeroturnaround.zip.ZipEntryCallback, java.nio.charset.Charset)`, a `ZipInputStream` instance is created](https://github.com/zeroturnaround/zt-zip/blob/f5b6a5a11ac0b0330e596f972ad9b9829a0c37a3/src/main/java/org/zeroturnaround/zip/ZipUtil.java#L708-L708) which is never closed. This causes a resource leakage or even [a native memory leak](http://kohsuke.org/2011/11/04/quiz-answer-memory-leak-in-java/).

**Comment by reinra** [comment]
Isn't it enough that the caller closes the `InputStream` which was passed in?

**Comment by lhotari** [comment]
@reinra No. The `ZipInputStream` will remain unclosed and there isn't a way to close it so that the native resources allocated by it could be released.

**Comment by reinra** [comment]
Thanks for pointing this out. To keep the semantics I would wrap the passed-in InputStream into an uncloseable InputStream, pass this to the ZipInputStream and close it so that the original stream remains unclosed.
We need to keep it open if it's actually an entry of another ZipInputStream e.g.

**Comment by lhotari** [comment]
@reinra Sounds like a good plan to fix this.

**Comment by reinra** [comment]
Is it ok now?

**Comment by lhotari** [comment]
@reinra Looks great. Thanks for the quick turnaround. :)
