### ISSUE TITLE
Please add pro guard configuration

### ISSUE THREAD

**Issue by ppamorim** [zeroturnaround/zt-zip#91]
Gradle has problems to resolve the library dependency, please add this on Readme to solve these conflicts:

```groovy
-dontwarn org.slf4j.**
```

**Comment by toomasr** [comment]
Can you provide an example with more context? The current README doesn't reference Gradle at all and this tip might not be that helpful.

**Comment by ppamorim** [comment]
As your library handles `Maven` setup, it handles `Gradle` setup too. This migration has zero effort.

**Comment by shelajev** [comment]
@ppamorim can you please elaborate on the changes you'd like to see in the README? Where should it be and how much info on the Gradle / proguard setup you think should be there? 
If you could send a pull request with the changes to the README you think are sufficient to explain how to make proguard in Gradle not warn about the slf4j classes, it'd be the most convenient! 

Thank you!

**Comment by reinra** [comment]
I think you shouldn't need to add `-dontwarn org.slf4j.**` if SLF4J is configured as a library for the ProGuard. You're actually configuring ProGuard in a wrong way.
