### ISSUE TITLE
packEntries does not accept folders

### ISSUE THREAD

**Issue by danechitoaie** [zeroturnaround/zt-zip#94]
Looks like pack entries only accepts files?
What I would need is to be able to use Ant directory scanner so I can exclude certain files and then feed that list to packEntries.

Or is there any other way to filter the contents of a folder and exclude some paths?

**Comment by reinra** [comment]
You can use
`void pack(File sourceDir, File targetZip, NameMapper mapper)`
and make `NameMapper` return null for the relative paths you wish to exclude.

**Comment by danechitoaie** [comment]
That's perfect. Thank you.
